query getData {
  books(pagination: { limit: 10000 }) {
    data {
      id
      attributes {
        name
        slug
        price
        description
        discountprice
        imgurl
        publication
        extradetails
        tags
        authors {
          data {
            attributes {
              name
              slug
            }
          }
        }
        categories {
          data {
            attributes {
              name
              slug
            }
          }
        }
      }
    }
  }
}
